/**
 * Shared helpers: the parity fixture schema and pure builders over it. This module
 * stays runtime-agnostic (no Node imports), so the browser suite shares it; the
 * filesystem loaders live in `node-fixtures.ts`.
 */

import type {
  Anchor as AnchorClass,
  ChannelConfig,
  ChannelInput,
  Direction as DirectionType,
  Fused,
  FuseConfigInit,
} from "../ts/index.js";
import { Anchor } from "../ts/index.js";

// The fixture schema, as generated by tests/parity_fixtures.rs (snake_case).
export interface FixtureGoodScore {
  readonly typical: number;
  readonly good: number;
  readonly weight: number;
}
export interface FixtureChannel {
  readonly key: string;
  readonly tag: string;
  readonly direction: DirectionType;
  readonly good_score: FixtureGoodScore | null;
}
export interface FixtureConfig {
  readonly discrimination: {
    readonly top_eps: number;
    readonly top_m: number;
    readonly min_distinct_values: number;
    readonly denom_floor_frac: number;
    readonly winsor_z: number;
    readonly min_count_for_z: number;
    readonly shrink_pool_size: number;
    readonly g_upper_bound: number;
    readonly g_floor: number;
    readonly g_slope: number;
    readonly g_deviation_keep: number;
  };
  readonly coupling: {
    readonly enabled: boolean;
    readonly discount_cap: number;
    readonly shrink_to_identity: number;
    readonly min_overlap: number;
    readonly min_reliability: number;
    readonly min_refreshes: number;
    readonly stratum_stability_max_var: number;
  };
  readonly fusion: { readonly rrf_eta: number; readonly min_g_dispersion: number };
  readonly decay: { readonly enabled: boolean; readonly factor: number };
  readonly baseline_mode: "z_score";
}
export interface FixtureInput {
  readonly key: string;
  readonly scored?: ReadonlyArray<readonly [string, number]>;
  readonly ranked?: readonly string[];
}
export interface FixtureAnchor {
  readonly candidates: readonly string[];
  readonly channels: readonly string[];
  readonly scores: ReadonlyArray<ReadonlyArray<number | null>>;
}
export interface FixtureExpected {
  readonly ranking: ReadonlyArray<readonly [string, number]>;
  readonly weights: Readonly<Record<string, number>>;
  readonly flags: Readonly<Record<string, string>>;
  readonly discrimination: Readonly<
    Record<
      string,
      {
        readonly g: number;
        readonly raw_separation: number | null;
        readonly top_m_average: number | null;
        readonly degenerate_separation: boolean;
        readonly reference_cold: boolean;
      }
    >
  >;
  readonly confidence: number;
  readonly conflict: number;
}
export type FixtureStep =
  | { readonly op: "fuse"; readonly inputs: readonly FixtureInput[]; readonly expected: FixtureExpected }
  | { readonly op: "refresh_coupling"; readonly anchor: FixtureAnchor };
export interface Fixture {
  readonly name: string;
  readonly kind: string;
  readonly channels?: readonly FixtureChannel[];
  readonly unregistered_channels?: readonly FixtureChannel[];
  readonly config?: FixtureConfig;
  readonly steps?: readonly FixtureStep[];
  readonly expected_state?: string;
  readonly prior_state?: string;
  readonly inputs?: readonly FixtureInput[];
  readonly expected?: FixtureExpected;
  readonly parts?: readonly string[];
  readonly expected_divergence?: {
    readonly per_channel: Readonly<Record<string, number>>;
    readonly max: number;
  };
  readonly start_state?: string;
  readonly ops?: ReadonlyArray<
    | { readonly op: "rekey"; readonly from: string; readonly to: string }
    | { readonly op: "decay"; readonly factor: number }
  >;
  readonly cases?: ReadonlyArray<{
    readonly name: string;
    readonly kind: "resume" | "merge" | "config";
    readonly channels?: readonly FixtureChannel[];
    readonly config?: FixtureConfig;
    readonly state?: string;
    readonly parts?: readonly string[];
    readonly error: string;
  }>;
}

export function makeChannel(d: FixtureChannel): ChannelConfig {
  return {
    id: { key: d.key, tag: d.tag },
    direction: d.direction,
    goodScore: d.good_score ?? undefined,
  };
}

/** Every channel the fixture mentions, registered or not, keyed by join handle. */
export function makeChannels(fixture: Fixture): Map<string, ChannelConfig> {
  const out = new Map<string, ChannelConfig>();
  for (const d of fixture.channels ?? []) {
    out.set(d.key, makeChannel(d));
  }
  for (const d of fixture.unregistered_channels ?? []) {
    out.set(d.key, makeChannel(d));
  }
  return out;
}

export function makeConfig(d: FixtureConfig): FuseConfigInit {
  return {
    discrimination: {
      topEps: d.discrimination.top_eps,
      topM: d.discrimination.top_m,
      minDistinctValues: d.discrimination.min_distinct_values,
      denomFloorFrac: d.discrimination.denom_floor_frac,
      winsorZ: d.discrimination.winsor_z,
      minCountForZ: d.discrimination.min_count_for_z,
      shrinkPoolSize: d.discrimination.shrink_pool_size,
      gUpperBound: d.discrimination.g_upper_bound,
      gFloor: d.discrimination.g_floor,
      gSlope: d.discrimination.g_slope,
      gDeviationKeep: d.discrimination.g_deviation_keep,
    },
    coupling: {
      enabled: d.coupling.enabled,
      discountCap: d.coupling.discount_cap,
      shrinkToIdentity: d.coupling.shrink_to_identity,
      minOverlap: d.coupling.min_overlap,
      minReliability: d.coupling.min_reliability,
      minRefreshes: d.coupling.min_refreshes,
      stratumStabilityMaxVar: d.coupling.stratum_stability_max_var,
    },
    fusion: {
      rrfEta: d.fusion.rrf_eta,
      minGDispersion: d.fusion.min_g_dispersion,
    },
    decay: { enabled: d.decay.enabled, factor: d.decay.factor },
    baselineMode: d.baseline_mode,
  };
}

export function makeInput(d: FixtureInput): ChannelInput {
  if (d.scored !== undefined) {
    return { key: d.key, scored: d.scored };
  }
  if (d.ranked !== undefined) {
    return { key: d.key, ranked: d.ranked };
  }
  throw new Error(`fixture input ${d.key} carries neither scored nor ranked`);
}

/**
 * Rebuilds the fixture's anchor through the public callback path, so the replay
 * exercises Anchor.build rather than injecting the matrix directly.
 */
export function makeAnchor(
  d: FixtureAnchor,
  channels: ReadonlyMap<string, ChannelConfig>,
): AnchorClass {
  const index = new Map(d.candidates.map((c, i) => [c, i]));
  const configs = d.channels.map((key) => {
    const config = channels.get(key);
    if (config === undefined) {
      throw new Error(`anchor references unknown channel ${key}`);
    }
    return config;
  });
  return Anchor.build(d.candidates, configs, (candidate, key) => {
    const row = d.channels.indexOf(key);
    const column = index.get(candidate);
    if (row < 0 || column === undefined) {
      throw new Error(`anchor lookup miss for ${candidate}/${key}`);
    }
    return d.scores[row]?.[column] ?? null;
  });
}

/** A Fused result in the fixture's expected-output schema, for exact comparison. */
export function fusedToFixture(f: Fused): FixtureExpected {
  return {
    ranking: f.ranking.map(([id, score]) => [id, score]),
    weights: Object.fromEntries(f.weights),
    flags: Object.fromEntries(f.flags),
    discrimination: Object.fromEntries(
      [...f.discrimination].map(([key, d]) => [
        key,
        {
          g: d.g,
          raw_separation: d.rawSeparation ?? null,
          top_m_average: d.topMAverage ?? null,
          degenerate_separation: d.degenerateSeparation,
          reference_cold: d.referenceCold,
        },
      ]),
    ),
    confidence: f.confidence,
    conflict: f.conflict,
  };
}
