/**
 * Replays the shared golden fixtures through the public TypeScript API, under
 * Node. The fixtures are generated by the Rust test `tests/parity_fixtures.rs` at
 * the repository root, from the same engine this package compiles in. Every
 * comparison is exact: wasm specifies IEEE-754 f64 arithmetic exactly and the
 * engine's transcendentals are pure-Rust libm, so rankings, weights, diagnostics,
 * and the serialized state bytes must match to the last bit. The browser suite
 * (`tests/browser/`) replays the same fixtures through the same assertions.
 */

import { describe, expect, test } from "vitest";

import { loadFixture } from "./node-fixtures.js";
import {
  replayMerge,
  replayRefusalCase,
  replaySession,
  replayStateOps,
  replayStateless,
} from "./replay.js";

const SESSION_FIXTURES = [
  "quickstart_three_channels.json",
  "ties_and_edge_inputs.json",
  "coupling_redundancy_discount.json",
  "decay_per_update.json",
];

describe("session fixtures", () => {
  test.each(SESSION_FIXTURES)("%s", (name) => {
    replaySession(loadFixture(name));
  });
});

test("stateless with a warm prior", () => {
  replayStateless(loadFixture("stateless_with_prior.json"));
});

test("merge reconciles and is commutative", () => {
  replayMerge(loadFixture("merge_reconcile.json"));
});

test("state ops: rekey then decay", () => {
  replayStateOps(loadFixture("state_ops_rekey_decay.json"));
});

describe("refusals", () => {
  const cases = loadFixture("refusals.json").cases ?? [];
  expect(cases.length).toBeGreaterThan(0);
  test.each(cases.map((c) => [c.name, c] as const))("%s", (_name, c) => {
    replayRefusalCase(c);
  });
});
