/**
 * Replays the shared golden fixtures through the public TypeScript API.
 *
 * The fixtures are generated by the Rust test `tests/parity_fixtures.rs` at the
 * repository root, from the same engine this package compiles in. Every comparison
 * is exact: wasm specifies IEEE-754 f64 arithmetic exactly and the engine's
 * transcendentals are pure-Rust libm, so rankings, weights, diagnostics, and the
 * serialized state bytes must match to the last bit.
 */

import { describe, expect, test } from "vitest";

import {
  ConfigError,
  Fuser,
  MergeError,
  MergePolicy,
  ResumeError,
  RuffleState,
} from "../ts/index.js";
import {
  fusedToFixture,
  loadFixture,
  makeAnchor,
  makeChannel,
  makeChannels,
  makeConfig,
  makeInput,
} from "./helpers.js";

const SESSION_FIXTURES = [
  "quickstart_three_channels.json",
  "ties_and_edge_inputs.json",
  "coupling_redundancy_discount.json",
  "decay_per_update.json",
];

describe("session fixtures", () => {
  test.each(SESSION_FIXTURES)("%s", (name) => {
    const fixture = loadFixture(name);
    expect(fixture.kind).toBe("session");
    const channels = makeChannels(fixture);
    const registered = (fixture.channels ?? []).map(makeChannel);
    const fuser = Fuser.create(registered, makeConfig(fixture.config!));
    try {
      for (const step of fixture.steps ?? []) {
        if (step.op === "fuse") {
          const fused = fuser.fuse(step.inputs.map(makeInput));
          expect(fusedToFixture(fused)).toEqual(step.expected);
        } else {
          fuser.refreshCoupling(makeAnchor(step.anchor, channels));
        }
      }
      expect(fuser.state.toJson()).toBe(fixture.expected_state);
    } finally {
      fuser.free();
    }
  });
});

test("stateless with a warm prior", () => {
  const fixture = loadFixture("stateless_with_prior.json");
  expect(fixture.kind).toBe("stateless");
  const registered = (fixture.channels ?? []).map(makeChannel);
  const prior = RuffleState.fromJson(fixture.prior_state!);

  const fused = Fuser.fuseStateless(
    (fixture.inputs ?? []).map(makeInput),
    registered,
    prior,
    makeConfig(fixture.config!),
  );

  expect(fusedToFixture(fused)).toEqual(fixture.expected);
  // The prior is read, never written.
  expect(prior.toJson()).toBe(fixture.prior_state);
});

test("merge reconciles and is commutative", () => {
  const fixture = loadFixture("merge_reconcile.json");
  expect(fixture.kind).toBe("merge");
  const parts = (fixture.parts ?? []).map((p) => RuffleState.fromJson(p));

  const [merged, divergence] = RuffleState.merge(parts, MergePolicy.Strict);
  expect(merged.toJson()).toBe(fixture.expected_state);
  expect({
    per_channel: Object.fromEntries(divergence.perChannel),
    max: divergence.max,
  }).toEqual(fixture.expected_divergence);

  const [remerged] = RuffleState.merge([...parts].reverse());
  expect(remerged.toJson()).toBe(fixture.expected_state);
});

test("state ops: rekey then decay", () => {
  const fixture = loadFixture("state_ops_rekey_decay.json");
  expect(fixture.kind).toBe("state_ops");
  let state = RuffleState.fromJson(fixture.start_state!);

  for (const op of fixture.ops ?? []) {
    if (op.op === "rekey") {
      state = state.rekey(op.from, op.to);
    } else {
      state = state.decay(op.factor);
    }
  }

  expect(state.toJson()).toBe(fixture.expected_state);
});

// Each refusal kind maps to the exception a binding must raise and a stable
// fragment of the engine's message.
const MISMATCH_FRAGMENTS: Record<string, string> = {
  format_version: "format version mismatch",
  fingerprint: "statistic fingerprint mismatch",
  direction_conflict: "direction conflict",
  tag: "semantic tag mismatch",
  empty: "empty set of states",
};
const CONFIG_FRAGMENTS: Record<string, string> = {
  invalid_fuse_config: "invalid fuse configuration",
  invalid_good_score: "good score is unusable",
  duplicate_channel_key: "duplicate channel key",
};

describe("refusals", () => {
  const cases = loadFixture("refusals.json").cases ?? [];
  test.each(cases.map((c) => [c.name, c] as const))("%s", (_name, c) => {
    if (c.kind === "resume") {
      const channels = (c.channels ?? []).map(makeChannel);
      const config = makeConfig(c.config!);
      const state = RuffleState.fromJson(c.state!);
      const fragment = MISMATCH_FRAGMENTS[c.error]!;
      expect(() => Fuser.resume(channels, state, config)).toThrowError(
        ResumeError,
      );
      expect(() => Fuser.resume(channels, state, config)).toThrowError(fragment);
      // fuseStateless runs the same gate against the prior.
      expect(() =>
        Fuser.fuseStateless([], channels, state, config),
      ).toThrowError(fragment);
    } else if (c.kind === "merge") {
      const parts = (c.parts ?? []).map((p) => RuffleState.fromJson(p));
      const fragment = MISMATCH_FRAGMENTS[c.error]!;
      expect(() => RuffleState.merge(parts)).toThrowError(MergeError);
      expect(() => RuffleState.merge(parts)).toThrowError(fragment);
    } else {
      const channels = (c.channels ?? []).map(makeChannel);
      const config = makeConfig(c.config!);
      const fragment = CONFIG_FRAGMENTS[c.error]!;
      expect(() => Fuser.create(channels, config)).toThrowError(ConfigError);
      expect(() => Fuser.create(channels, config)).toThrowError(fragment);
    }
  });
});
