"""Typed surface of the private compiled extension module.

The runtime module is built from ``bindings/python/src/lib.rs``; this stub mirrors
its signatures for type checkers, with the boundary shapes defined in
``ruffle._types``. Everything here is private plumbing behind the public package.
"""

from collections.abc import Sequence

from ruffle._types import (
    ChannelDict,
    DivergenceDict,
    FuseConfigDict,
    FusedDict,
    InputSpec,
)

__version__: str
FORMAT_VERSION: int
STAT_VERSION: int

class RuffleError(Exception): ...
class ConfigError(RuffleError): ...
class ResumeError(RuffleError): ...
class MergeError(RuffleError): ...

class Fuser:
    def __init__(self, channels: list[ChannelDict], config: FuseConfigDict) -> None: ...
    @staticmethod
    def resume(channels: list[ChannelDict], config: FuseConfigDict, state: str) -> Fuser: ...
    def fuse(self, inputs: Sequence[InputSpec]) -> FusedDict: ...
    @staticmethod
    def fuse_stateless(
        inputs: Sequence[InputSpec],
        channels: list[ChannelDict],
        config: FuseConfigDict,
        prior: str,
    ) -> FusedDict: ...
    def refresh_coupling(
        self,
        channels: Sequence[tuple[str, str]],
        rows: Sequence[list[float | None]],
    ) -> None: ...
    def state_json(self) -> str: ...

def state_canonicalize(state: str) -> str: ...
def state_merge(parts: list[str]) -> tuple[str, DivergenceDict]: ...
def state_divergence(a: str, b: str) -> DivergenceDict: ...
def state_rekey(state: str, from_key: str, to_key: str) -> str: ...
def state_decay(state: str, factor: float) -> str: ...
def default_config() -> FuseConfigDict: ...
