"""fit_base_weights: golden parity with the numpy reference, and the edge
semantics the design pins.

The golden fixtures were generated by the evaluation harness's numpy
reference implementation (evals/cache/improve/make_fit_fixtures.py): real
scifact queries plus a handcrafted case with tied fused scores straddling
the rank-10 cutoff, where any tie-break divergence between the pure-Python
helper and the reference moves the metric.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from ruffle import FittedBaseWeights, fit_base_weights

FIXTURES = Path(__file__).parent / "fixtures" / "fit"


def load_fixture(name: str) -> dict:
    return json.loads((FIXTURES / name).read_text())


def as_scored(runs: dict) -> dict:
    return {
        key: {
            qid: [(doc, float(score)) for doc, score in items]
            for qid, items in per_query.items()
        }
        for key, per_query in runs.items()
    }


@pytest.mark.parametrize("name", ["scifact32.json", "ties.json"])
def test_golden_parity_with_the_numpy_reference(name: str) -> None:
    fixture = load_fixture(name)
    runs = as_scored(fixture["runs"])
    for case in fixture["cases"]:
        result = fit_base_weights(
            runs,
            fixture["qrels"],
            eta=case["eta"],
            floor=case["floor"],
            guard=case["guard"],
        )
        expected = case["expected"]
        assert dict(result.weights) == pytest.approx(expected["weights"], abs=1e-12)
        assert result.fell_back == expected["fell_back"]
        assert result.heldout_fitted == pytest.approx(expected["heldout_fitted"], abs=1e-12)
        assert result.heldout_uniform == pytest.approx(expected["heldout_uniform"], abs=1e-12)
        assert result.n == expected["n"]
        assert result.n_dropped == expected["n_dropped"]


def test_deterministic_and_typed() -> None:
    fixture = load_fixture("ties.json")
    runs = as_scored(fixture["runs"])
    first = fit_base_weights(runs, fixture["qrels"], eta=20.0)
    second = fit_base_weights(runs, fixture["qrels"], eta=20.0)
    assert first == second
    assert isinstance(first, FittedBaseWeights)
    assert sum(first.weights.values()) == pytest.approx(1.0, abs=1e-12)


def test_ranked_input_matches_scored_when_scores_are_strictly_ordered() -> None:
    fixture = load_fixture("scifact32.json")
    scored = as_scored(fixture["runs"])
    ranked = {
        key: {
            qid: [doc for doc, _ in sorted(items, key=lambda it: -it[1])]
            for qid, items in per_query.items()
        }
        for key, per_query in scored.items()
    }
    a = fit_base_weights(scored, fixture["qrels"], eta=20.0)
    b = fit_base_weights(ranked, fixture["qrels"], eta=20.0)
    # scifact channel scores are strictly ordered within each truncated run,
    # so midranks equal positions and the two input forms agree exactly.
    assert dict(a.weights) == dict(b.weights)
    assert a.heldout_fitted == pytest.approx(b.heldout_fitted, abs=1e-12)


def test_single_channel_is_refused() -> None:
    with pytest.raises(ValueError, match="two channels"):
        fit_base_weights({"only": {"q": ["a", "b"]}}, {"q": {"a": 1}}, eta=20.0)


def test_infeasible_floor_for_channel_count_is_refused() -> None:
    runs = {k: {"q1": ["a", "b"], "q2": ["b", "a"]} for k in "abcde"}
    qrels = {"q1": {"a": 1}, "q2": {"b": 1}}
    with pytest.raises(ValueError, match="no non-uniform"):
        fit_base_weights(runs, qrels, eta=20.0, floor=0.2)  # N=5 at 0.2
    fit_base_weights(runs, qrels, eta=20.0, floor=0.1)  # N=5 at 0.1 is legal


def test_bad_eta_and_floor_are_refused() -> None:
    runs = {"a": {"q": ["x"]}, "b": {"q": ["x"]}}
    qrels = {"q": {"x": 1}}
    with pytest.raises(ValueError, match="eta"):
        fit_base_weights(runs, qrels, eta=float("nan"))
    with pytest.raises(ValueError, match="eta"):
        fit_base_weights(runs, qrels, eta=-1.0)
    with pytest.raises(ValueError, match="floor"):
        fit_base_weights(runs, qrels, eta=20.0, floor=0.6)


def test_tiny_or_zero_gain_sample_is_refused_and_drops_are_counted() -> None:
    runs = {"a": {"q1": ["x"], "q2": ["y"]}, "b": {"q1": ["x"], "q2": ["y"]}}
    with pytest.raises(ValueError, match="fewer than two"):
        fit_base_weights(runs, {"q1": {"x": 1}}, eta=20.0)
    with pytest.raises(ValueError, match="fewer than two"):
        # zero-gain judgments drop both queries
        fit_base_weights(runs, {"q1": {"x": 0}, "q2": {"y": 0}}, eta=20.0)
    three = {
        "a": {"q1": ["x"], "q2": ["y"], "q3": ["x"]},
        "b": {"q1": ["x"], "q2": ["y"], "q3": ["y"]},
    }
    result = fit_base_weights(
        three, {"q1": {"x": 1}, "q2": {"y": 1}, "q3": {"x": 0}}, eta=20.0
    )
    assert result.n == 2
    assert result.n_dropped == 1


def test_qrels_runs_intersection_and_missing_channel_queries() -> None:
    runs = {
        "a": {"q1": ["x", "y"], "q2": ["y"]},
        "b": {"q1": ["y", "x"]},  # q2 missing entirely: empty contribution
    }
    qrels = {"q1": {"x": 2}, "q2": {"y": 1}, "q9": {"z": 3}}  # q9 not in runs
    result = fit_base_weights(runs, qrels, eta=20.0)
    assert result.n == 2  # q1 and q2; q9 contributes no docs and is dropped
    assert result.n_dropped == 1


def test_guard_falls_back_on_noise() -> None:
    # Judgments that alternate which channel is right: no stable tilt exists,
    # the held-out estimate cannot beat uniform, and the guard returns
    # uniform weights with the flag set.
    runs = {
        "a": {f"q{i}": [f"d{i}a", f"d{i}b"] for i in range(8)},
        "b": {f"q{i}": [f"d{i}b", f"d{i}a"] for i in range(8)},
    }
    qrels = {f"q{i}": {(f"d{i}a" if i % 2 == 0 else f"d{i}b"): 1} for i in range(8)}
    result = fit_base_weights(runs, qrels, eta=20.0)
    assert result.fell_back
    assert set(result.weights.values()) == {0.5}
    unguarded = fit_base_weights(runs, qrels, eta=20.0, guard=False)
    assert not unguarded.fell_back
