"""Replays the shared golden fixtures through the public Python API.

The fixtures are generated by the Rust test ``tests/parity_fixtures.rs`` at the
repository root, from the same engine this package compiles in. Every comparison is
exact: the engine is bit-deterministic, so rankings, weights, diagnostics, and the
serialized state bytes must match to the last bit, on every platform.
"""

from __future__ import annotations

from typing import Any

import pytest
import ruffle
from ruffle import Fuser, MergePolicy, RuffleState

from .conftest import (
    fused_to_dict,
    load_fixture,
    make_anchor,
    make_channel,
    make_channels,
    make_config,
    make_input,
)

SESSION_FIXTURES = [
    "quickstart_three_channels.json",
    "ties_and_edge_inputs.json",
    "coupling_redundancy_discount.json",
    "decay_per_update.json",
]


@pytest.mark.parametrize("name", SESSION_FIXTURES)
def test_session_fixture(name: str) -> None:
    fixture = load_fixture(name)
    assert fixture["kind"] == "session"
    channels = make_channels(fixture)
    registered = [make_channel(d) for d in fixture["channels"]]
    fuser = Fuser(registered, make_config(fixture["config"]))

    for step in fixture["steps"]:
        if step["op"] == "fuse":
            inputs = [make_input(d, channels) for d in step["inputs"]]
            fused = fuser.fuse(inputs)
            assert fused_to_dict(fused) == step["expected"]
        elif step["op"] == "refresh_coupling":
            fuser.refresh_coupling(make_anchor(step["anchor"], channels))
        else:
            raise AssertionError(f"unknown step {step['op']!r}")

    assert fuser.state.to_json() == fixture["expected_state"]


def test_stateless_fixture() -> None:
    fixture = load_fixture("stateless_with_prior.json")
    assert fixture["kind"] == "stateless"
    channels = make_channels(fixture)
    registered = [make_channel(d) for d in fixture["channels"]]
    prior = RuffleState.from_json(fixture["prior_state"])

    fused = Fuser.fuse_stateless(
        [make_input(d, channels) for d in fixture["inputs"]],
        registered,
        prior,
        make_config(fixture["config"]),
    )

    assert fused_to_dict(fused) == fixture["expected"]
    # The prior is read, never written.
    assert prior.to_json() == fixture["prior_state"]


def test_merge_fixture() -> None:
    fixture = load_fixture("merge_reconcile.json")
    assert fixture["kind"] == "merge"
    parts = [RuffleState.from_json(p) for p in fixture["parts"]]

    merged, divergence = RuffleState.merge(parts, MergePolicy.STRICT)
    assert merged.to_json() == fixture["expected_state"]
    assert {
        "per_channel": dict(divergence.per_channel),
        "max": divergence.max,
    } == fixture["expected_divergence"]

    # The merge is commutative: the reversed order produces identical bytes.
    remerged, _ = RuffleState.merge(list(reversed(parts)))
    assert remerged.to_json() == fixture["expected_state"]


def test_state_ops_fixture() -> None:
    fixture = load_fixture("state_ops_rekey_decay.json")
    assert fixture["kind"] == "state_ops"
    state = RuffleState.from_json(fixture["start_state"])

    for op in fixture["ops"]:
        if op["op"] == "rekey":
            state.rekey(op["from"], op["to"])
        elif op["op"] == "decay":
            state.decay(op["factor"])
        else:
            raise AssertionError(f"unknown op {op['op']!r}")

    assert state.to_json() == fixture["expected_state"]


# Each refusal kind maps to the exception a binding must raise and a stable fragment
# of the engine's message.
_MISMATCH_FRAGMENTS = {
    "format_version": "format version mismatch",
    "fingerprint": "statistic fingerprint mismatch",
    "direction_conflict": "direction conflict",
    "tag": "semantic tag mismatch",
    "empty": "empty set of states",
}
_CONFIG_FRAGMENTS = {
    "invalid_fuse_config": "invalid fuse configuration",
    "invalid_good_score": "good score is unusable",
    "duplicate_channel_key": "duplicate channel key",
}


def _refusal_cases() -> list[dict[str, Any]]:
    return list(load_fixture("refusals.json")["cases"])


@pytest.mark.parametrize("case", _refusal_cases(), ids=lambda c: str(c["name"]))
def test_refusal_fixture(case: dict[str, Any]) -> None:
    kind = case["kind"]
    if kind == "resume":
        channels = [make_channel(d) for d in case["channels"]]
        config = make_config(case["config"])
        state = RuffleState.from_json(case["state"])
        expected: type[Exception] = ruffle.ResumeError
        with pytest.raises(expected, match=_MISMATCH_FRAGMENTS[case["error"]]):
            Fuser.resume(channels, state, config)
        # fuse_stateless runs the same gate against the prior.
        with pytest.raises(expected, match=_MISMATCH_FRAGMENTS[case["error"]]):
            Fuser.fuse_stateless([], channels, state, config)
    elif kind == "merge":
        parts = [RuffleState.from_json(p) for p in case["parts"]]
        with pytest.raises(ruffle.MergeError, match=_MISMATCH_FRAGMENTS[case["error"]]):
            RuffleState.merge(parts)
    elif kind == "config":
        channels = [make_channel(d) for d in case["channels"]]
        config = make_config(case["config"])
        with pytest.raises(ruffle.ConfigError, match=_CONFIG_FRAGMENTS[case["error"]]):
            Fuser(channels, config)
    else:
        raise AssertionError(f"unknown refusal kind {kind!r}")
